[package]
name = "asstosrt_wasm"
version = "0.2.0"
authors = ["Shell Chen <me@sorz.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
yew = "0.17"
web-sys = "0.3"
wasm-bindgen = "0.2"
regex = "1.3"
lazy_static = "1.4"
encoding = "0.2"
chardet = "0.2"
simplecc = "0.2"
crc = "1.8.1"